version: "3.9"
services:
  nginx:
    image: nginx:1.25-bookworm
    # Temporarly use 8000 for production
    ports:
        - 8000:80
    volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        - static_volume:/server/store/static
        - media_volume:/server/store/media
  server:
    image: django-store_server_prod
    build:
      context: ./
      dockerfile: ./Dockerfile
    entrypoint: /server/server-entrypoint.sh
    volumes:
      - static_volume:/server/store/static
      - media_volume:/server/store/media
    env_file: .env_prod
  worker:
    image: django-store_worker_prod
    build:
      context: ./
      dockerfile: ./Dockerfile
    entrypoint: /server/worker-entrypoint.sh
    volumes:
      - static_volume:/server/store/static
      - media_volume:/server/store/media
    env_file: .env_prod
    depends_on:
      - server
    #depends_on:
    #   - db
    #environment:
    #  DEBUG: 'True'
volumes:
    static_volume: {}
    media_volume: {}
