version: "3.9"
services:
  nginx:
    image: nginx:1.25-bookworm
    ports:
        - 888:80
    volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        - static_volume:/server/store/static
  server:
    build:
      context: ./
      dockerfile: ./Dockerfile
    entrypoint: /server/server-entrypoint.sh
    volumes:
      - static_volume:/server/store/static
    env_file: .env_prod
  worker:
    build:
      context: ./
      dockerfile: ./Dockerfile
    entrypoint: /server/worker-entrypoint.sh
    volumes:
      - static_volume:/server/store/static
    env_file: .env_prod
    depends_on:
      - server
    #depends_on:
    #   - db
    #environment:
    #  DEBUG: 'True'
volumes:
    static_volume: {}
