version: "3.9"
services:
  nginx:
    image: nginx:1.25-bookworm
    ports:
        - 80:80
    volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        - static_volume:/server/store/static
  server:
    build:
      context: ./
      dockerfile: ./Dockerfile
    entrypoint: /server/server-entrypoint.sh
    volumes:
      - ./:/server
    ports:
      - "8000:8000"
    env_file: .env
  worker:
    build:
      context: ./
      dockerfile: ./Dockerfile
    entrypoint: /server/worker-entrypoint.sh
    volumes:
      - ./:/server
    env_file: .env
    depends_on:
      - server
    #depends_on:
    #   - db
    #environment:
    #  DEBUG: 'True'
