version: "3.9"
services:
  server:
    image: django-store_server_debug
    container: django-store_server_debug
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: python ./store/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/server
    ports:
      - "8000:8000"
    env_file: .env
  worker:
    image: django-store_worker_debug
    container: django-store_worker_debug
    build:
      context: ./
      dockerfile: ./Dockerfile
    entrypoint: /server/worker-entrypoint.sh
    volumes:
      - ./:/server
    env_file: .env
    depends_on:
      - server
    #depends_on:
    #   - db
    #environment:
    #  DEBUG: 'True'
