# Generated by Django 4.2.1 on 2023-09-19 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("basket_history", models.JSONField(default=dict)),
                ("first_name", models.CharField(max_length=62)),
                ("last_name", models.CharField(max_length=62)),
                ("delivery_address", models.CharField(max_length=254)),
                ("email", models.EmailField(max_length=254)),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[
                            (0, "Created"),
                            (1, "Paid"),
                            (2, "On way"),
                            (3, "Delivered"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
