# Generated by Django 4.2.1 on 2023-08-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_basket_productbasket"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productcategory",
            name="category",
        ),
        migrations.RemoveField(
            model_name="productcategory",
            name="product",
        ),
        migrations.AddField(
            model_name="basket",
            name="products",
            field=models.ManyToManyField(blank=True, null=True, to="products.product"),
        ),
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(blank=True, null=True, to="products.category"),
        ),
        migrations.DeleteModel(
            name="ProductBasket",
        ),
        migrations.DeleteModel(
            name="ProductCategory",
        ),
    ]
