# Generated by Django 4.2.1 on 2023-08-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_remove_product_categories_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(blank=True, null=True, to="products.category"),
        ),
        migrations.DeleteModel(
            name="ProductCategory",
        ),
    ]
