# Generated by Django 4.2.1 on 2023-09-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_product_categories_delete_productcategory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
        migrations.AlterField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(to="products.category"),
        ),
    ]
